### ISSUE TITLE
Add dotnet runtime tests to pipeline

### ISSUE THREAD

**Issue by vtikoo** [deislabs/mystikos#10]
Blockers:
- Due to number of tests(p0  ~2.7k, p0+p1 ~10k) using rootfs is too slow. Each test takes ~15 seconds, running just the p0 tests would take over 8 hours. Once the ext2 PR #4 is merged, migrate `samples/coreclr` to use ext2 fs.
- Resolution to #9

**Comment by bodzhang** [comment]
Closed with https://github.com/deislabs/mystikos/pull/2 merged.
