### ISSUE TITLE
Unix-domain sockets does not support dup()

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#1085]
Unix-domain sockets does not yet support ``dup()``, which may not be meaningful for Unix-domain sockets.

**Comment by radhikaj** [comment]
No use case for this currently.

**Comment by bodzhang** [comment]
During process clone, dup() call can be invoked on an AF_LOCAL socket.

PR #1109 added Unix-Domain (AF_LOCAL) socket dup() support.
