### ISSUE TITLE
pipeline times out when trying to run binary in docker container

### ISSUE THREAD

**Issue by salsal97** [deislabs/mystikos#123]
run: https://openenclave.visualstudio.com/ACC-Services/_build/results?buildId=5192&view=logs&j=ab477ad6-9781-5b54-82ca-a0141b26726e&t=a1e294d4-8895-5a45-41ff-022cede0621b&l=5453
branch: https://github.com/salsal97/mystikos/tree/network.timout_issue 

/agent/_work/1/s/build/bin/myst exec-sgx --roothash=/agent/_work/1/s/tests/network/roothash /agent/_work/1/s/tests/network/rootfs /app/sockperf ping-pong
Unable to find image 'sagoel/sockperf:1.0' locally
1.0: Pulling from sagoel/sockperf
5d20c808ce19: Already exists
299c398f0ae0: Pulling fs layer
5ab2cd3a6ce9: Pulling fs layer
f880eae6f8e3: Pulling fs layer
18d873e0823f: Pulling fs layer
18d873e0823f: Waiting
sockperf: == version #3.7-4.gitb3df070d5649.dirty == 
sockperf[CLIENT] send on:sockperf: using recvfrom() to block on socket(s)

[ 0] IP = 0.0.0.0         PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
f880eae6f8e3: Verifying Checksum
f880eae6f8e3: Download complete
299c398f0ae0: Verifying Checksum
299c398f0ae0: Download complete
299c398f0ae0: Pull complete
sockperf: Starting test...
sockperf: Start sleep for 1 seconds 450 useconds
18d873e0823f: Download complete
5ab2cd3a6ce9: Verifying Checksum
5ab2cd3a6ce9: Download complete
5ab2cd3a6ce9: Pull complete
f880eae6f8e3: Pull complete
18d873e0823f: Pull complete
Digest: sha256:554092adb5893a3417b08f4a1714178cba220f653d153e87513146107e582271
Status: Downloaded newer image for sagoel/sockperf:1.0
sockperf: == version #3.7-8.git7ac842d55281 == 
sockperf: [SERVER] listen on:
[ 0] IP = 0.0.0.0         PORT = 11111 # UDP
sockperf: Warmup stage (sending a few dummy messages)...
sockperf: [tid 1] using recvfrom() to block on socket(s)

**Comment by paulcallen** [comment]
@salsal97 is this slow and a higher timeout in pipeline solves the issue, or is it actually hang.
Has it been resolved?

**Comment by AevaOnline** [comment]
@salsal97 checking in -- is this still an issue? If so, is it a timeout issue (perhaps solved by caching or increasing test timeout),  or is it a broken test?

**Comment by salsal97** [comment]
@paulcallen as far as I recall, it would actually hang and not go further even on increasing the timeout 
@AevaOnline I think I accidentally cleaned the branch that would reproduce this issue, and the pipeline run was cleaned as well :/

**Comment by paulcallen** [comment]
lets close for now until we can reproduce it.
