### ISSUE TITLE
[Tracking] ltp/kernel/testcases/fs tests face unhandled syscalls 

### ISSUE THREAD

**Issue by salsal97** [deislabs/mystikos#139]
/ltp/testcases/kernel/fs/fs_fill/fs_fill        unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/fsstress/fsstress      unhandled syscall: SYS_umask()
/ltp/testcases/kernel/fs/inode/inode02          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/inode/inode01          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/openfile/openfile      unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/proc/proc01            unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/stream/stream05        unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/stream/stream04        unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/stream/stream03        unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/stream/stream02        unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/stream/stream01        unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/ftest/ftest07          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/ftest/ftest08          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/ftest/ftest04          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/ftest/ftest01          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/ftest/ftest03          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/ftest/ftest06          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/ftest/ftest02          unhandled syscall: SYS_chown()
/ltp/testcases/kernel/fs/doio/doio              unhandled syscall: SYS_umask()
/ltp/testcases/kernel/fs/doio/growfiles         unhandled syscall: SYS_fork()
/ltp/testcases/kernel/fs/doio/iogen             unhandled syscall: SYS_umask()
/ltp/testcases/kernel/fs/read_all/read_all      unhandled syscall: SYS_setitimer()

**Comment by paulcallen** [comment]
- chown should be in place, although we only have 1 identity currently. Will require identity work to extend more
- umask, we assume everthing is running as root. Anything more requires identity to be added
- missing setitimer 
- missing fork

**Comment by jxyang** [comment]
Please update the list. @salsal97

**Comment by paulcallen** [comment]
@salsal97 please can we have another run of these tests

**Comment by paulcallen** [comment]
all these syscalls have not been implemented.
