### ISSUE TITLE
 gettid: symbol not found

### ISSUE THREAD

**Issue by aep** [deislabs/mystikos#1401]
is there a list of supported symbols?

this is from stock mariadb on alpine-3:

```
myst exec-sgx --roothash=roothash ext2rootfs /usr/bin/mariadbd
Error relocating /usr/bin/mariadbd: gettid: symbol not found
```

not sure if this is supposed to work,

**Comment by vtikoo** [comment]
Thats interesting, I can't seem to find a `gettid` function in musl C library. We've had some gap with C library functions present in glibc, but not in musl in the past. Could you can share your Dockerfile and some repro steps?

Also during creation of the rootfs, you could run `scripts/appbuilder` with -p option. That should print unsupported glibc symbols present in the application - https://github.com/deislabs/mystikos/blob/main/scripts/appbuilder#L27.

**Comment by radhikaj** [comment]
@aep Please let us know if you need additional help.
