### ISSUE TITLE
Thread number over 32 issue

### ISSUE THREAD

**Issue by praenubilus** [deislabs/mystikos#141]
The thread number of myst application cannot be configured unless it is packaged. 
In the `config.json` (e.g. https://github.com/deislabs/mystikos/blob/main/solutions/dotnet/config.json), if the `"NumUserThreads"` exceeds 32, mystikos will crash. 

In some applications like webserver requires more than 32 threads when the thread pool is initialized. For example the cpprestsdk having such configuration by default (https://github.com/microsoft/cpprestsdk/issues/428).

A larger number of user threads is needed.

**Comment by paulcallen** [comment]
This requires a change to OE to increase number of threads
