### ISSUE TITLE
*** kernel panic: malloc.c(34): _dlmalloc_abort(): dlmalloc failed

### ISSUE THREAD

**Issue by MohamedFadhel11** [deislabs/mystikos#1466]
Hello !!

I'm running an AI model, which is not to big (Lenet5 model),  using the Pytorch framework and I 'm using this model for inference and when I'm running it with mystikos I get this error: 

*** kernel panic: malloc.c(34): _dlmalloc_abort(): dlmalloc failed
0x7f912bf35305: __myst_panic()
0x7f912bf2b2d5: _dlmalloc_abort()
0x7f912bf2eeb5: dlrealloc()
0x7f912bf66878: myst_buf_reserve()
0x7f912bf66902: myst_buf_resize()
0x7f912bf05e7d: _fs_write()
0x7f912befd59c: _fs_write()
0x7f912bf36401: myst_syscall_write()
0x7f912bf3e79f: _SYS_write()
0x7f912bf47a80: _syscall()
0x7f912bf6c975: __morestack()
*** Kernel segmentation fault 
0x7f912bf2b2d5: _dlmalloc_abort()
0x7f912bf2eeb5: dlrealloc()
0x7f912bf66878: myst_buf_reserve()
0x7f912bf66902: myst_buf_resize()
0x7f912bf05e7d: _fs_write()
0x7f912befd59c: _fs_write()
0x7f912bf36401: myst_syscall_write()
0x7f912bf3e79f: _SYS_write()
# Hardware: 
OS: ubuntu20.04
SGX_version: SGX1
mystikos: latest
# To reproduce: 
1) Building the docker image and the appdir 
2) Building the file system with mkcpio 
3) Running the app with myst exec-sgx with memory-size= 2Gb and thread stack size = 1Mb (even when I increase the memory size or the thread stack size the problem persist. 
Else, could you please give me the best practices of running Deep Learning models on mystikos. 

Thank you for your time.

**Comment by vtikoo** [comment]
Hi @MohamedFadhel11, can you try ext2 file system instead of cpio? You can take a look at `myst mkext2` for help on this subcommand.

**Comment by MohamedFadhel11** [comment]
Hi , Thank you for your response I just changed to mkext2 and it worked. Just I have questions concerning the parameter of --memory-size that we pass the command  sgx-exec: 

1) what is this size exactly because as we know that SGX1 is limited to 128MB of memory size but I can set it to 2 Gb and 3 Gb and it still work. 
2) what is it's limitation because I tried 4 Gb and still working.

Thank you for your time !!

**Comment by vtikoo** [comment]
Sorry for the delayed response @MohamedFadhel11.

Linux supports enclaves greater than the physical EPC size via paging. However, if the resident set size for the enclave application is larger than the physical EPC there will be performance impact due to swapping.
There is no limitation as such, but we've seen enclave processes being terminated by kernel's OOM killer beyond a certain point.
