### ISSUE TITLE
Memory usage of python apps inside SGX enclave

### ISSUE THREAD

**Issue by MohamedFadhel11** [deislabs/mystikos#1467]
Hello community !!

Is there any tool that helps me to know the memory usage of a python application inside the SGX enclave in mystikos. I tried with tracemalloc and memory profile but they gave me results over 128MB (which is the limit of SGX1). I need a tool that helps me to know how much memory the python code is using inside that 128MB memory.

Thank you for you help.

**Comment by vtikoo** [comment]
I'm afraid standard tools like tracemalloc which work for regular virtual memory might not work with enclave apps, as EPC memory is a resource managed by the SGX driver.

If the application being run is something you control, you can instrument your code with `sysinfo()` or read `/proc/meminfo` to get statistics on memory usage. That might give you some guidance on how much to tune your `--memory-size` parameter.

**Comment by vtikoo** [comment]
Mystikos memory manager could track the total size of active memory mappings, and print out the maximum value it saw during an application's lifetime at shutdown. But we don't support this currently.

cc: @mikbras

**Comment by vtikoo** [comment]
Fixed by #1493
