### ISSUE TITLE
strace crashes while munmapping an abandoned child thread 

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#150]
Munmapping an abandoned child thread is performed on a temporary stack that is available in libc and kernel. But when strace is on, we need to go to OE/host for printing the messages. The OE/host code are in a separated space that has no access to the temporary stack, causing crash.

**Comment by jxyang** [comment]
This is blocking any dotnet application from generating syscall trace logs.

**Comment by paulcallen** [comment]
one option is at point strace will no longer work, disable it

**Comment by jxyang** [comment]
We need this desperately for debugging dotnet applications.

**Comment by paulcallen** [comment]
this was fixed my mike with the kernel stack check-in
