### ISSUE TITLE
DNS Resolver configuration for Mystikos App network access

### ISSUE THREAD

**Issue by bodzhang** [deislabs/mystikos#158]
Current Mystikos implementation requires the App rootfs to include a /etc/resolv.conf file with a predetermined nameserver IP address. See makefile example [here](https://github.com/deislabs/mystikos/blob/main/tests/curl/Makefile).

The target platform a Mystikos App executes on might require a DNS Resolver configuration different from the predetermined nameserver IP setting selected at Mystikos App build time. 

Current Mystikos implementation utilizes the OS network stack. The DNS Resolver configuration in the OS can also be utilized, including any DNS name resolution caching optimizations provided by the OS. 

The DNS Service and URL resolution are not part of the Mystikos App TCB. Mystikos App should utilize TLS, with the TLS endpoint inside the trusted execution environment,  when the network peer needs to be authenticated and/or the network traffic needs to be protected.

**Comment by paulcallen** [comment]
one way to implement is to have set entries in the config that point to files that if accessed, pulls the file directly from the host filestystem and not from the rootfs that is currently mounted

**Comment by bodzhang** [comment]
With PR [#365](https://github.com/deislabs/mystikos/pull/365), the Linux hostfs' /etc/resolv.conf file can be mapped and accessed by the code inside the Mystikos app when needed. 

The content of the hostfs /etc/resolv.conf file can be cached by the Mystikos kernel and file system layer after the first access, but in theory, hostfs' /etc/resolv.conf file can be updated through OS or other system level SW stack update, while the Mystikos app is running. Caching the content might cause unexpected failure.

It's OK to include a hardcoded resolv.conf file (at Mytikos app build time), as a fallback, in case the app developer or container runtime environment configuration missed the hostfs /etc/resolv.conf mounting configuration by mistake, as long as the hostfs /etc/resolv.conf takes precedence when configured. But the implementation might require more changes than PR #365.

**Comment by jxyang** [comment]
From the design discussions with Paul below, I think the file added through the mount point always shadows the ones in existing FS. In that sense, PR #365 should not need additional work to enforce the precedence of which /etc/resolv.conf is visible to the app.

> If you mount a source directory over a target directory that has files in then you can no longer see the old files, only the new ones. I believe mount -bind allows you to see what is already there as well.
I assume the same is also the case with a file being mounted into target directory where the file exists... that one will become hidden and the newly mounted one will be seen.

**Comment by bodzhang** [comment]
Address by PR #449
