### ISSUE TITLE
sched_getaffinity() support does not provide accurate info of available CPUs

### ISSUE THREAD

**Issue by bodzhang** [deislabs/mystikos#191]
Current implementation in Mystikos returns an affinity mask indicating only one CPU is available.  

Many high level programing language runtime and apps use sched_getaffinity() to detect how many CPUs are available to perform parallel operations. Indicating that only one CPU is available would likely cause the runtimes or apps running inside Mystikos to disable performance benefiting parallel operations.

For Mystikos-SGX, an OCALL to invoke sched_getaffinity() call on the OS side probably is sufficient to return the proper affinity mask.

**Comment by paulcallen** [comment]
getaffinity seems moderate, setting can fake success if needed
Number of CPUs can be added to configuration to set how many. But ability to limit may be more tricky.

**Comment by bodzhang** [comment]
Addressed by PR [#345](https://github.com/deislabs/mystikos/pull/345)
