### ISSUE TITLE
userid in enclave issue

### ISSUE THREAD

**Issue by praenubilus** [deislabs/mystikos#20]
When running Memcached server in enclave, the service will try to detect userid and decide if root user is needed. When running in myst OS, this seems being messed up. @vtikoo can you add more details?

Here is the link to memcached source when the issue being triggered.
https://github.com/memcached/memcached/blob/c472369fed5981ba8c004d426cee62d5165c47ca/memcached.c#L5562

**Comment by jxyang** [comment]
The can be work around by changing the default user id to 1 from 0.

https://github.com/deislabs/mystikos/blob/151d32fc3ec9e759932545b9f7f4d61e4ece5b6e/include/myst/id.h#L7

Maybe we do want to stop being root (but still enjoy root privileges).

**Comment by jxyang** [comment]
This PR will allow us to run memcached with `-u <username>`. But with the default user id 0, we run into another unhandled syscall: `SYS_setgroups`.

Setting default user id to 1 would solve the problem.

**Comment by praenubilus** [comment]
So what is the default userid now? With `-u <username>`, how can I assign userid 0? should I use `-u root`?

**Comment by paulcallen** [comment]
This should work now the identity check-in is done
