### ISSUE TITLE
Make getting-started doc a little cleaner

### ISSUE THREAD

**Issue by AevaOnline** [deislabs/mystikos#200]
https://github.com/deislabs/mystikos/blob/main/doc/user-getting-started-c.md#build-the-program

This could be done with `gcc`; there's no need to use `myst-gcc`.

We should also make it clear in the doc that directly compiling an app like this will only work for very simple apps with few / no system dependencies.

**Comment by jxyang** [comment]
Would you submit a PR? @AevaOnline

**Comment by jxyang** [comment]
Replaced references to `myst-gcc` with `gcc` in get-started guides.
