### ISSUE TITLE
Support SYS_prctl

### ISSUE THREAD

**Issue by praenubilus** [deislabs/mystikos#21]
Missing `syscall prtctl` support for memcached/redis solution.

![Screenshot from 2021-01-19 16-37-44](https://user-images.githubusercontent.com/547418/105339006-107dd680-5b91-11eb-916b-871757f7ee0a.png)

**Comment by vtikoo** [comment]
openjdk 8 runtime makes  a prctl with `PR_SET_SPECULATION_CTRL` option.

**Comment by vtikoo** [comment]
@praenubilus the above stacktrace is from redis. Can you confirm if you saw this issue in memcached as well?
Text searches for prctl or pthread_setname_np don't yield any results on the memcached repo.

**Comment by praenubilus** [comment]
I can confirm memcached need the same syscall

**Comment by paulcallen** [comment]
marking this as lower severity as all blocking usages have been handled

**Comment by praenubilus** [comment]
I believe this issue can be closed.
