### ISSUE TITLE
epoll doesn't work when the socket FD is established from a client outside the enclave

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#234]
This is illustrated by modifying https://github.com/deislabs/mystikos/tree/main/tests/epoll with the attached patch:
[epoll-bug.txt](https://github.com/deislabs/mystikos/files/6246043/epoll-bug.txt)

To run the server first: make && make tests
To run the client second: gcc client.c -o client && ./client

The client side error message indicates the server failed to respond to client request:
 
> client: client.c:59: run_client: Assertion `"read() failed" == NULL' failed.

This is blocking [memcached](https://github.com/deislabs/mystikos/pull/199) even after all issues identified are resolved.

**Comment by praenubilus** [comment]
Will this issue being solved recently?

**Comment by jxyang** [comment]
No longer reproducible. I think it's fixed by #https://github.com/deislabs/mystikos/commit/41080a1a32252d61e047e581deb9f7a5384050e2
