### ISSUE TITLE
Remove NumStackPages NumTCS from config and documentation

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#242]
We now set the NumTCS to 1024 and the NumStackPages to 2. We should now remove ``NumStackPages`` and ``NumTCS`` from the config and documentation.

**Comment by bodzhang** [comment]
The NumTCS is now hardcoded to 1024. It's not expected that many apps need more than several hundreds concurrent threads. If compatibility issue is encountered in the future, will need to reconsider whether NumTCS should be made configurable.

**Comment by bodzhang** [comment]
Addressed by PR #669
