### ISSUE TITLE
fcntl(F_SETFD/F_GETFD) is not working on "/dev/urandom"

### ISSUE THREAD

**Issue by bodzhang** [deislabs/mystikos#247]
In the current implementation, "/dev/urandom" is special cased in [syscall.c](https://github.com/deislabs/mystikos/blob/db4722d71b7e01f20f5295882cf51632b41b2a51/kernel/syscall.c#L706). 

fcntl(...F_SETFD/F_GETFD,..) operation on "/dev/urandom" failed.

**Comment by mikbras** [comment]
This will be addressed by the upcoming /dev work where /dev files will be an actual file-system type.

**Comment by bodzhang** [comment]
Python 3.8.1 (on Ubuntu) file utility use fcntl(...,F_SETFD,...) when opening a file, to [set/clear FD_CLOEXEC](https://github.com/python/cpython/blob/9976834f807ea63ca51bc4f89be457d734148682/Python/fileutils.c#L1313).

FD_CLOEXEC is explained [here]( https://www.gnu.org/software/libc/manual/html_node/Descriptor-Flags.html)

**Comment by bodzhang** [comment]
Python3.8.1 plus numpy also calls fstat() on "/dev/urandom".

**Comment by paulcallen** [comment]
this will likely be handled as part of implementing the /dev implementation

**Comment by jxyang** [comment]
Is this fixed by #290? @vtikoo

**Comment by vtikoo** [comment]
@jxyang The /dev implementation adds support  for `fcntl` operation. However, clearing the `FD_CLOEXEC` flag wasn't supported by ramfs and ext2 fcntl implementation. #342 addresses that.

**Comment by vtikoo** [comment]
Closed by #323 and #342.
