### ISSUE TITLE
myst-appbuilder Dockerfile command error invalid reference format: repository name must be lowercase

### ISSUE THREAD

**Issue by agowdamsft** [deislabs/mystikos#274]
The myst build is complaining I have repo names with uppercase which isint the case. I dont have folder names with uppercase. 
The error needs improvement to state what the tool to build is looking for.
![image](https://user-images.githubusercontent.com/36743184/114263053-26cd4e80-9998-11eb-85a5-742e0814b30e.png)
![image](https://user-images.githubusercontent.com/36743184/114263064-36e52e00-9998-11eb-82ef-c4efc79a5533.png)

**Comment by praenubilus** [comment]
I met the exact error last week. And I believe this is a bug introduced by last build script update. I can provide a fix today or tomorrow.

**Comment by praenubilus** [comment]
@agowdamsft , your case is a little bit strange. Which version of mystikos are you using? The problem happens here: https://github.com/deislabs/mystikos/blob/ab1206b9cc4cce3178a9ad6fa6cfcc432bd8802d/scripts/appbuilder#L129 

The actual problem I want to discuss is after recent updates for appbuilder script, the Dockerfile named different from "Dockerfile" will not be recognized if `-d` option is not used. For examle `Dockerfile.stage1` will be treated as a URL at this line
https://github.com/deislabs/mystikos/blob/ab1206b9cc4cce3178a9ad6fa6cfcc432bd8802d/scripts/appbuilder#L76
`USE_DOCKERFILE` flag will be set to false and raise the same error mentioned above.

**Comment by jxyang** [comment]
Is this with the latest Mystikos? I can run the command `myst-appbuilder Dockerfile` in solutions/msgpack_c without problems.
