### ISSUE TITLE
Unable to load non-debug mode enclave applications  

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#279]
If we set `DEBUG` to 0 in config.json, Mystikos fails to load the application with the following message:

> 2021-04-12T21:51:01+0000.931659Z [(H)ERROR] tid(0x7f2963974b80) | Enclave image was signed without debug flag but is being loaded with OE_ENCLAVE_FLAG_DEBUG set in oe_create_enclave call
 (oe_result_t=OE_DEBUG_DOWNGRADE) [/mystikos/third_party/openenclave/openenclave/host/sgx/create.c:oe_sgx_build_enclave:896]
2021-04-12T21:51:01+0000.931789Z [(H)ERROR] tid(0x7f2963974b80) | :OE_DEBUG_DOWNGRADE [/mystikos/third_party/openenclave/openenclave/host/sgx/create.c:oe_create_enclave:1129]

**Comment by mikbras** [comment]
Does it fail on signed or unsigned enclaves?

**Comment by jxyang** [comment]
Signed and packaged applications.

**Comment by jxyang** [comment]
How does OE load an non-debug application? [Here](https://github.com/deislabs/mystikos/blob/8e34564d17464a0e22164c1b8387446037dd01f9/tools/myst/host/exec.c#L209) we hardcoded the DEBUG flag,

**Comment by jxyang** [comment]
There seems to be no support in OE for non-debug mode applications. We have to determine the mode ourselves and create an enclave with the correct flag.

**Comment by mikbras** [comment]
> How does OE load an non-debug application? [Here](https://github.com/deislabs/mystikos/blob/8e34564d17464a0e22164c1b8387446037dd01f9/tools/myst/host/exec.c#L209) we hardcoded the DEBUG flag,

Do we visit that code path when running signed apps?

**Comment by jxyang** [comment]
Yes, that's the only path prior to creation of enclaves.

**Comment by paulcallen** [comment]
we have all the information from the enclave at the point we launch the enclave so we can pull that configuration before creating the enclave so it is always right.

**Comment by mingweishih** [comment]
This issue should be resolved in the current OE master per https://github.com/openenclave/openenclave/pull/3965/.

**Comment by jxyang** [comment]
Thanks for the quick fix. @mingweishih

**Comment by jxyang** [comment]
We need to either cherry pick OE's fix or update our OE branch. And use `OE_ENCLAVE_FLAG_DEBUG_AUTO` in our host launcher.

**Comment by jxyang** [comment]
Fixed by #554
