### ISSUE TITLE
Add samples to the PR pipeline 

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#300]
The samples are not included in the quality gate. It can be gradually degrade into a waste yard if we keep adding them without testing the old ones. It will reflect poorly on the project if the first sample a potential user tried is broken.

**Comment by paulcallen** [comment]
We need to clean up the samples to just samples that work. Maybe one for each sample.
Samples should be installed as part of the install of Mystikos.
Samples should therefore be tested by installing the Mystikos SDK package, set up variables against the install, then check the samples build and run.

**Comment by jxyang** [comment]
We will keep samples as an experimental area and try to convert stable ones to either solutions or tests.

Drop this for now.
