### ISSUE TITLE
appbuilder should output the progress while building the container image

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#305]
The current implementation prints nothing while building the image with `docker build`, leaving the user in dark and wonder whether the tool is hanging or not. This is bad user experience. It's also less helpful with debugging pipeline failures.

**Comment by praenubilus** [comment]
I have raised this question long time before. I suggest add an parameter/option for appbuilder to enable/disable the silent mode of docker build. I can include this in my PR https://github.com/deislabs/mystikos/pull/280
