### ISSUE TITLE
Consider supporting MAP_FIXED

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#314]
Currently the memory manager only supports **mmap()** for two cases:
- The addr parameter is null and MAP_FIXED is not given.
- The addr parameter is non-null, MAP_FIXED is given, and the region is already mapped.

The second case is to support mapping of files, where an initial call was done to reserve the memory and a second call (with MAP_FIXED) was done to map part of that region onto a file.

**Comment by bodzhang** [comment]
With PR #545 , mmap() supports

- The addr parameter is null and MAP_FIXED is not given.
- The addr parameter is non-null, MAP_FIXED is given, and the region is already mapped.
- The addr parameter is non-null, MAP_FIXED is not given.

The third case is to support mapping with preferred address. In current implementation, if the preferred mapping is not part of any region already mapped, the memory manager will choose the address location.

**Comment by bodzhang** [comment]
@mikbras, do you consider this issue addressed?

**Comment by paulcallen** [comment]
closing as the important cases we can support are implemented
