### ISSUE TITLE
General support of Python libraries

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#370]
We want to support popular Python libraries that are used by our customers. Here is the preliminary list:

- [x] numpy: scientific computing library:                       **core test suite passing rate: 99.5%**
- [x] pandas:  data analysis tools: **full test suite passing rate: 99.9%**
- [x] logzero: logger
- [x] pycrypto: crypto library
- [x] pyjwt: JSON Web Token (JWT) implementation
- [x] flask: web framework 
- [x] nose: test framework 
- [x] redis: in-memory cache management 
- [x] pyodbc: 
         - Database driver with support for MSI
- [x] sqlalchemy:
       - SQL Toolkit and Object Relational Mapper
       - same error as pyodbc
- [x] pycurl:
        - Python implementation of curl
- [x] authlib:
        - for building OAuth and OpenID Connect servers
        - Use fork (works with or w/o pseudo fork)
- [ ] gunicorn:
        - Python WSGI HTTP Server 
        - Use fork
        - Crash due to GIL
 - [ ] fabric: 
        - remote shell commands over SSH
        - crash (reason tbd)

Here is the docker file I used to create the docker image and rootfs that include above packages:
 ```dockerfile
FROM ubuntu:18.04

# Build Python from source. The packaged Python executable is non-PIE.
# See issue https://bugs.launchpad.net/ubuntu/+source/python2.7/+bug/1452115
RUN apt update && apt install -y curl gnupg2 &&\
    curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - &&\
    curl https://packages.microsoft.com/config/ubuntu/18.04/prod.list > /etc/apt/sources.list.d/mssql-release.list &&\
    apt update && \
    apt install -y wget vim &&\
    ACCEPT_EULA=Y apt install -y msodbcsql17 &&\
    wget -q https://repo.continuum.io/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh &&\
    chmod 755 Miniconda3-py38_4.8.2-Linux-x86_64.sh &&\
    ./Miniconda3-py38_4.8.2-Linux-x86_64.sh -b -p /miniconda &&\
    /miniconda/bin/pip install numpy logzero &&\
    /miniconda/bin/conda install -y -c miniconda pyodbc pandas redis pycrypto pycurl gunicorn pyjwt nose fabric3 authlib sqlalchemy &&\
    /miniconda/bin/pip install pyca &&\
    /miniconda/bin/python3 --version
    
WORKDIR /app
COPY ./app.py .
COPY ./nosetest.py .
COPY ./fabfile.py .

ENV PYTHONUNBUFFERED=1

CMD ["/miniconda/bin/python3", "/app/app.py"]
```

**Comment by jxyang** [comment]
Add support for pyodbc, sqlalchemy, and pycurl with PR #411

**Comment by paulcallen** [comment]
Full fork() support is out of scope so gunicorn cannot be supported if it needs this. It does not work with just fork/exec mode.
We are not perusing SSH.
Therefore closing this as we have gone as far as are planning on.
