### ISSUE TITLE
The patched OE code invokes registered Page_Fault exception handler based on untrusted input from the host

### ISSUE THREAD

**Issue by bodzhang** [deislabs/mystikos#399]
The [patched code](https://github.com/openenclave/openenclave/blob/222719e43c3e14b1a01c817a00ba77f1ded1fce5/enclave/core/sgx/exception.c#L393)  sets exception type as OE_EXCEPTION_PAGE_FAULT, and exception address based on input (`oe_exception_record`) from the untrusted host, and will invoke any registered PAGE_FAULT exception handler, on SGX1 CPU. The untrusted host can invoke this code flow at any time, whether or not any exception is encountered inside the SGX Enclave, or forge the exception address.

This patch should only be enabled for debug purpose.

**Comment by jxyang** [comment]
Fixed with `Support the CapturePFGPExceptions preference openenclave/openenclave#4068` on mystikos.v4
