### ISSUE TITLE
make sleep interruptible by signals

### ISSUE THREAD

**Issue by paulcallen** [deislabs/mystikos#408]
calling exit() from any thread should terminate the process. Calling pthread_exit() kills just the thread it is on and other threads continue as normal -- meaning this would exit the main thread but other threads should continue until all threads call pthread_exit(), or one of the threads call exit()
The problem in this case is that when we exit the non-main thread it does not kill other threads -- something we have been discussing for a long time.

Writing a simple piece of code can show a rather unfortunate crash:
```c
#include <stdio.h>
#include <stdlib.h>
#include <pthread.h>
#include <stdio.h>
#include <unistd.h>

void* func(void* arg)
{
    printf("thread...\n");
    exit(1);
    //pthread_exit(NULL);
    return NULL;
}

int main()
{
    pthread_t t;

    pthread_create(&t, NULL, func, NULL);
//    pthread_join(t, NULL);

    printf("before sleep...\n");
    sleep(5);
    printf("after sleep...\n");

    return 0;
}
```

The second thread goes away in this case, but the main thread is left in a broken state because it too was not killed.
The main thread in this example hangs because printf() in the main thread is trying to get a CRT lock that in the second exiting thread locked.
The sample hangs the same with the pthread_join although I did not debug that scenario.
Any threads in the kernel when exit is called need to be SIGKILL sending to them, which will hopefully cause any locks to unlock and then they get killed and never return back to the application.

**Comment by bodzhang** [comment]
The default signal handler implementation has similar challenges. For unhandled signal, the current implementation jumps to the [exit code](https://github.com/bodzhang/mystikos/blob/787a59799f706404f7733fee092ecc0ba8668f02/kernel/enter.c#L843), which might wait for other threads to exit. The current default handler implementation does not signal other threads to exit before the jump. The implementation might not work.

**Comment by jxyang** [comment]
The `exit` function does make a syscall `exit_group` which is supposed to shutdown the process. The problem is that the main process still needs to finish the sleeping (5 seconds in this case) before `exit_group` can proceed.

We need to make `sleep` interruptible by signals.

**Comment by paulcallen** [comment]
I believe this is fixed at this point
