### ISSUE TITLE
Race condition in musl libc __umapself.c

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#409]
There seems to be a race condition if two threads call ``__umapself`` at the same time. This occurs when both threads set the static variables in this module and start executing on the same static stack. See statics below.

```C++
#include "atomic.h"
#include "syscall.h"
/* cheat and reuse CRTJMP macro from dynlink code */
#include "dynlink.h"

static void *unmap_base;
static size_t unmap_size;
static char shared_stack[4096];

static void do_unmap()
{
        __syscall(SYS_munmap, unmap_base, unmap_size);
        __syscall(SYS_exit);
}

void __unmapself(void *base, size_t size)
{
        char *stack = shared_stack + sizeof shared_stack;
        stack -= (uintptr_t)stack % 16;
        unmap_base = base;
        unmap_size = size;
        CRTJMP(do_unmap, stack);
}
```

We discussed this and proposed a new extended Mystikos syscall to solve the problem.

```
__syscall(SYS_myst_munmap_on_exit, addr, length);
```

This syscall requests to unmap memory later during thread exit handling (where addr and length are saved in the corresponding thread structure temporarily).

This allows the calling stack to be used for the ``SYS_exit``.

Then ``__unmapself`` could be replaced with the following.

```C++
void __unmapself(void *base, size_t size)
{
        __syscall(SYS_myst_munmap_on_exit, base, size);
        __syscall(SYS_exit, 0);
}
```

**Comment by radhikaj** [comment]
@paulcallen  - Can you add the PR to this issue and close?

**Comment by radhikaj** [comment]
Fix is here: https://github.com/deislabs/mystikos/pull/707
