### ISSUE TITLE
Kernel dependencies in ext2

### ISSUE THREAD

**Issue by vtikoo** [deislabs/mystikos#410]
As part of the identity support, 4 kernel(libmystkernel.so) dependencies have crept into libmystext2.a.
- myst_syscall_geteuid
- myst_syscall_getegid
- myst_thread_self
- check_thread_group_membership

This is requiring stubs to be added to /tests/plain/ext2, as this test does not link against libmystkernel.so.

**Comment by paulcallen** [comment]
this is expected as ext2 is only meant to be used within the kernel, not the host.  There are tests that use this outside the kernel, and the right way of solving this is to add stubs in the code.
