### ISSUE TITLE
Code-Scanning-Issues: cpp/array-arg-size-mismatch

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#441]
CodeQL Rule ID | File Path | Line | Alert URL
-- | -- | -- | --
cpp/array-arg-size-mismatch | ext2/ext2.c | 3784 | https://github.com/deislabs/mystikos/security/code-scanning/1277
cpp/array-arg-size-mismatch | ext2/ext2.c | 4019 | https://github.com/deislabs/mystikos/security/code-scanning/1276
cpp/array-arg-size-mismatch | kernel/syscall.c | 2021 | https://github.com/deislabs/mystikos/security/code-scanning/2293
cpp/array-arg-size-mismatch | kernel/syscall.c | 2578 | https://github.com/deislabs/mystikos/security/code-scanning/1278

**cpp/array-arg-size-mismatch**
https://codeql.github.com/codeql-query-help/cpp/cpp-array-arg-size-mismatch/

**Comment by mikbras** [comment]
Resolved by https://github.com/deislabs/mystikos/pull/481
