### ISSUE TITLE
Code-Scanning-Issues: cpp/constant-comparison

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#442]
Rule ID | Location Path | Line | Alert URL
-- | -- | -- | --
cpp/constant-comparison | kernel/exec.c | 212 | https://github.com/deislabs/mystikos/security/code-scanning/978
cpp/constant-comparison | tools/myst/host/host.c | 182 | https://github.com/deislabs/mystikos/security/code-scanning/1071
cpp/constant-comparison | utils/fdops.c | 68 | https://github.com/deislabs/mystikos/security/code-scanning/1073
cpp/constant-comparison | utils/fdops.c | 145 | https://github.com/deislabs/mystikos/security/code-scanning/1072

https://codeql.github.com/codeql-query-help/cpp/cpp-constant-comparison/

**Comment by mikbras** [comment]
Resolved by https://github.com/deislabs/mystikos/pull/481
