### ISSUE TITLE
Code-Scanning-Issues: cpp/integer-multiplication-cast-to-long

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#443]
Rule ID | Location Path | Line | Alert URL
-- | -- | -- | --
cpp/integer-multiplication-cast-to-long | ext2/ext2.c | 936 | https://github.com/deislabs/mystikos/security/code-scanning/125
cpp/integer-multiplication-cast-to-long | ext2/ext2.c | 3147 | https://github.com/deislabs/mystikos/security/code-scanning/124

https://codeql.github.com/codeql-query-help/cpp/cpp-integer-multiplication-cast-to-long/

**Comment by mikbras** [comment]
Resolved by https://github.com/deislabs/mystikos/pull/481
