### ISSUE TITLE
Code-Scanning-Issues: cpp/signed-overflow-check

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#444]
Rule ID | Location Path | Line | Alert URL
-- | -- | -- | --
cpp/signed-overflow-check | tools/myst/enc/clock.c | 149 | https://github.com/deislabs/mystikos/security/code-scanning/137

https://codeql.github.com/codeql-query-help/cpp/cpp-signed-overflow-check/

**Comment by mikbras** [comment]
Resolved by https://github.com/deislabs/mystikos/pull/481
