### ISSUE TITLE
Code-Scanning-Issues: cpp/suspicious-sizeof 

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#445]
Rule ID | Location Path | Line | Alert URL
-- | -- | -- | --
cpp/suspicious-sizeof | utils/cpio.c | 656 | https://github.com/deislabs/mystikos/security/code-scanning/2024

https://codeql.github.com/codeql-query-help/cpp/cpp-suspicious-add-sizeof/

**Comment by mikbras** [comment]
Resolved by https://github.com/deislabs/mystikos/pull/481
