### ISSUE TITLE
Code-Scanning-Issues: cpp/toctou-race-condition

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#446]
Rule ID | Location Path | Line | Alert URL
-- | -- | -- | --
cpp/toctou-race-condition | utils/cpio.c | 734 | https://github.com/deislabs/mystikos/security/code-scanning/1997

https://codeql.github.com/codeql-query-help/cpp/cpp-toctou-race-condition/

**Comment by mikbras** [comment]
Resolved by https://github.com/deislabs/mystikos/pull/481
