### ISSUE TITLE
Code-Scanning-Issues: cpp/unsigned-comparison-zero

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#447]
Rule ID | Location Path | Line | Alert URL
-- | -- | -- | --
cpp/unsigned-comparison-zero | ext2/ext2.c | 1692 | https://github.com/deislabs/mystikos/security/code-scanning/1178
cpp/unsigned-comparison-zero | ext2/ext2.c | 1666 | https://github.com/deislabs/mystikos/security/code-scanning/1177
cpp/unsigned-comparison-zero | ext2/ext2.c | 1889 | https://github.com/deislabs/mystikos/security/code-scanning/1176
cpp/unsigned-comparison-zero | ext2/ext2.c | 1813 | https://github.com/deislabs/mystikos/security/code-scanning/1175

https://codeql.github.com/codeql-query-help/cpp/cpp-unsigned-comparison-zero/

**Comment by mikbras** [comment]
Resolved by https://github.com/deislabs/mystikos/pull/481
