### ISSUE TITLE
Mystikos process gets killed for bigger rootfs sizes on DC2s_v2

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#47]
myst package and myst exec fail with a rootfs of 746M.

**Comment by paulcallen** [comment]
need to investigate what is having problems. We can increase various memory sizes, but this seems to be more than just that.

**Comment by jxyang** [comment]
@vtikoo  Can you verify this is still reproducible?

**Comment by jxyang** [comment]
This is reproducible on a DC2s with a Python hello world app.

**Comment by paulcallen** [comment]
wondering if this is an out of memory issue where a failure is not causing the process to shutdown properly.

**Comment by jxyang** [comment]
This is no longer reproducible. Tried a few memory\-hungary applications and all passed.
