### ISSUE TITLE
GCOV will generate garbled characters in file name

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#48]
Currently gcov lib version(7.5.0) and gcov util code will generate garbled characters in file names for code coverage. This will

1. crash the dotnet solution running and,
2. generate bunch of unusable gcda and gcno files.

That error happens systematically for kernel and utils and possible for other components. That makes code coverage result not consumable.

Some thoughts and findings:

1. The problem is possible introduced by code update. The last normal code coverage report can be found is around Oct 20th, 2020. After that the nightly pipeline crashed for a long period(around half month). Unfortunately, nightly pipeline does not retain jobs running before October.
1. The currently used gcov version is built from GCC 7.5.0, other versions will not generate gcda and gnco files(verified by Xuejun). And also the code coverage report generation script need an overhaul. It may not process all gcda and gcno files correctly.

**Comment by bodzhang** [comment]
Addressed by PR [#335](https://github.com/deislabs/mystikos/pull/335)
