### ISSUE TITLE
Prefix _exec_package options with --myst

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#499]
I noticed that there are several options in ``_exec_package()`` that should be prefixed with ``--myst-`` to avoid conflict with application options. I added one called ``--myst-rootfs=<filename>`` but I noticed others without the prefix.

**Comment by paulcallen** [comment]
suggest: ./xyz --myst-options -strace -etrace -mem-size=1000g -- -a -f -g

**Comment by radhikaj** [comment]
In packaged mode, we have an option to say ignore commandline options and instead use config options in "ApplicationParameters" and set AllowHostApplicationParameters=false. 
Fixing this will be a breaking change, so for now developers can use this workaround.
