### ISSUE TITLE
Pseudo fork: hang when the parent doesn't wait

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#515]
For the following test case, on Linux, the parent would exit even though it didn't wait for the child. However, with Mystikos, the main process just hangs. 

```c
void fork_child(char* path, char* child_argv[]) 
{
    if (fork() == 0)
    {
      sleep(1);
       printf("*** inside child.. reading argv[0]: %s\n", child_argv[0]);
       exit(2);
    }
}

int main()
{
    char* path = "/bin/fork_child";
    char* child_argv[] = {path, NULL};
    fork_child(path, child_argv);

    child_argv[0] = NULL;
    return 0;
}
```

**Comment by paulcallen** [comment]
SIGHUP is now sent to all children when a parent process is shutting down.
Children can block this and continue working, but we still need to wait for any remaining child because we cannot unmap all this processes memory pages because the child is also still using them

**Comment by paulcallen** [comment]
lets verify. The child here is killing itself in the fork and this should work.

**Comment by radhikaj** [comment]
This is fixed.
