### ISSUE TITLE
Get started with dotnet  doc doesn't work with .NET framework 5.0.2

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#52]
Here is the error I get when trying to run the docker container:
 
> myst/bin/dotnet /app/sum.dll 1 2 3 Failed to create CoreCLR, HRESULT: 0x8007000E Enclave /tmp/mystQ53eX5/lib/openenclave/mystenc.so returned -2147450743

**Comment by Francis-Liu** [comment]
@jxyang I came across a similar failure when running mystikos enclave with default user-space memory. Setting `--user-mem-size` to at least 1g fixed the issue.

**Comment by paulcallen** [comment]
@jxyang going to check if this is still a problem

**Comment by jxyang** [comment]
This is still true with the following Dockerfile:
```
# stage 1: build
FROM mcr.microsoft.com/dotnet/sdk:5.0 AS build
WORKDIR /app
COPY . .
RUN dotnet publish -o publish -r linux-musl-x64

# stage 2: run
FROM mcr.microsoft.com/dotnet/aspnet:5.0-alpine
WORKDIR /app

RUN apk add --no-cache icu-libs
COPY --from=build /app/publish .

ENTRYPOINT [ "dotnet", "/app/sum.dll", "1", "2", "3" ]
```

**Comment by vtikoo** [comment]
> myst/bin/dotnet /app/sum.dll 1 2 3 Failed to create CoreCLR, HRESULT: 0x8007000E Enclave

0x8007000E is out of memory error code in dotnet runtime. As @Francis-Liu has observed above, running with higher memory size should fix this.
