### ISSUE TITLE
apps no longer crash and return nonzero status to the command line

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#567]
I added the following line to the ``getcwd`` test.

```
     asssert(0);
```

The test prints the assertion message but exits with a zero status. This will lead to false test passes in the pipeline.

**Comment by mikbras** [comment]
This also fails to fail (returns zero status to command line)

```
*((int*)0) = 0;
```

**Comment by jxyang** [comment]
Fixed by #561
