### ISSUE TITLE
rust sample run failed

### ISSUE THREAD

**Issue by mingweishih** [deislabs/mystikos#582]
Steps
1. make
2. make run

Results
```
/home/mingwei/mystikos/scripts/mkrootfs ./hello_world rootfs
/home/mingwei/mystikos/build/bin/myst exec-sgx  rootfs /bin/hello_world
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by /bin/hello_world)
Makefile:16: recipe for target 'run' failed
make: *** [run] Error 127
```

Environment
- Ubuntu 18.04

**Comment by jxyang** [comment]
`mkrootfs` is not recommended.

We should follow the [guide](https://github.com/deislabs/mystikos/blob/main/doc/user-getting-started-rust.md) and copy `ld-linux-x86-64.so.2` into appdir.

**Comment by jxyang** [comment]
Now we have `samples/rust_docker` that does the right thing: creating appdir from a Dockerfile, we should remove the broken `samples/rust`

**Comment by paulcallen** [comment]
recommendation to remove this one
