### ISSUE TITLE
running out of memory when creating many thousands of threads

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#598]
The following program runs out of memory when creating thousands of threads in a loop.

```C++
#include <pthread.h>
#include <stdio.h>
#include <assert.h>

_Atomic(size_t) _num;

void* start(void* arg)
{
    printf("child: %zu\n", _num++);
    return arg;
}

#define NTHREADS 512
#define NITERATIONS 100

int main()
{
    pthread_t threads[NTHREADS];

    for (size_t j = 0; j < NITERATIONS; j++)
    {
        for (size_t i = 0; i < NTHREADS; i++)
        {
            assert(pthread_create(&threads[i], NULL, start, NULL) == 0);
            assert(pthread_join(threads[i], NULL) == 0);
        }
    }

    return 0;
}
```

The program exits with this:

```
myst_run_thread_ecall(): failed: res=0 retval=-12
Makefile:16: recipe for target 'test2' failed
make: *** [test2] Aborted (core dumped)
```

The failure occurs in ``kernel/thread.c`` in ``myst_run_thread()`` when that function calls ``memalign`` to allocate a stack.

The error can be overcome by increasing the memory size, but that does not explain why the memory is exhausted when thread memory should be reclaimed.

The root of the problem is that ``myst_thread_t`` structures are no longer freed during ongoing execution. They are only freed during shutdown, so eventually all memory will be exhausted. They used to be freed during zombification on maximum list size overflow.

**Comment by paulcallen** [comment]
This is now fixed as myst_thread_t structures are deleted when the thread goes away
