### ISSUE TITLE
SYS_connect: return EFAULT on a bad sockaddr input

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#599]
/ltp/testcases/kernel/syscalls/connect/connect01 fails because it deliberately passed in `sockaddr = 0xffffffffffffffff` and expected a return of `EFAULT`.

**Comment by vtikoo** [comment]
Related to #405

**Comment by salsal97** [comment]
Revert this PR once fixed: https://github.com/deislabs/mystikos/pull/600

**Comment by mingweishih** [comment]
Fixed by #683
