### ISSUE TITLE
Core dump while building a fresh cloned mystikos 

### ISSUE THREAD

**Issue by jxyang** [deislabs/mystikos#637]
Here are the error messages:

> mkdir -p /home/xuejun/mystikos/tests/libc/appdir/bin
/home/xuejun/mystikos/build/musl/bin/musl-gcc -Wall -o /home/xuejun/mystikos/tests/libc/appdir/bin/run run.c
/home/xuejun/mystikos/build/bin/myst mkext2 --force /home/xuejun/mystikos/tests/libc/appdir /home/xuejun/mystikos/tests/libc/rootfs
do_write_internal: Permission denied while opening "core" to copy
__populate_fs: Permission denied while writing file "core"
mke2fs: Permission denied while populating file system
/home/xuejun/mystikos/build/bin/myst: error: failed to execute command: /sbin/mke2fs -q /home/xuejun/mystikos/tests/libc/rootfs -d /home/xuejun/mystikos/tests/libc/appdir
Makefile:44: recipe for target '/home/xuejun/mystikos/tests/libc/rootfs' failed

**Comment by anakrish** [comment]
@jxyang I might have run into a similar issue when my disk was almost out of space; predominantly consumed by /var/lib/docker.
