### ISSUE TITLE
Let's use a Tagging taxonomy

### ISSUE THREAD

**Issue by AevaOnline** [deislabs/mystikos#66]
To help with finding, tracking, and triaging issues and PRs, I suggest we adopt a thoughtful taxonomy for Tags -- and document it! By way of a [strawman proposal](https://en.wikipedia.org/wiki/Straw_man), I'd like to propose the following:

Tags may be grouped with prefixes to describe the category of the Tag itself, and a suffix to describe the category of the Issue, separated by a slash ("/"). 

- prefix **status**: indicates a status for an issue, such as: _status/new_, _status/triaged_, _status/rejected_, _status/in-progress_, and _status/stale_.
- prefix **type**: indicates the type of issue, such as: _type/bug_, _type/discussion_, _type/feature_, _type/process_.
- prefix **area**: indicates which part of the codebase the issue relates to, such as: _area/docs_, _area/filesystem_, _area/kernel_, _area/cli_.

In this way, Issues and PRs needing attention can be located efficiently by those with the relevant knowledge to attend to them, for example by searching for the intersection of  _status/new_ and _area/kernel_ to identify new kernel bugs that need to be triaged. 

Thoughts? Feedback? Suggestions for improvement?

**Comment by paulcallen** [comment]
We have a set of labels set and are now using them
