### ISSUE TITLE
RFD: suggested improvements in "TEE-aware example"

### ISSUE THREAD

**Issue by AevaOnline** [deislabs/mystikos#68]
The `user-getting-started-tee-aware.md` example is, perhaps, the most compelling (certainly the most technically deep) of our example docs right now. However, the _story_ doesn't quite seem to land, and I think it could be better.

Suggestion:
- add a section at the top, just before the **Problem Statement**, which describes the overall "story". What will this demo _do_? What makes it valuable, unique, or interesting among all the demos?
- add a section telling folks what the walkthrough will do. Describe it in simple bullet points. Something like this fictitious example sentence: "In this example, you will: create two enclave processes, define a secret, pass it to one enclave, and access it from the other".
- This was the first mention in the docs of `MRSIGNER`. I think new users won't know what this is, so we should explain it (maybe with an inserted section), and it would be helpful to link to further reading on the topic (is there some in this repo? in OE-SDK? or on Intel's site?)

**Comment by jxyang** [comment]
Fixed.
