### ISSUE TITLE
libc tests w/ posix spawn: flaky execution on linux target

### ISSUE THREAD

**Issue by salsal97** [deislabs/mystikos#71]
Ensure libc tests consistently pass
On failure, test name of failed test should be displayed

**Comment by paulcallen** [comment]
checking status of successfully spawned test that passes does not always return the correct process exit status

**Comment by paulcallen** [comment]
@salsal97 are we still having flakiness or can we close this now

**Comment by paulcallen** [comment]
please reactivate if we still have an issue, but at this time the tests seem to pass reliably
