### ISSUE TITLE
Executable built with clang (clang CRT libraries?) fails to load in exec-sgx mode.

### ISSUE THREAD

**Issue by mrragava** [deislabs/mystikos#719]
//hello.c
#include <stdio.h>
int main()
{
    printf("Hello world from Mystikos!\n");
    return 0;
}
^EOF

$ mkdir appdir
$ clang -g -o appdir/hello hello.c
$ myst mkcpio ./appdir rootfs
$ myst exec-sgx ./rootfs /hello

**>>> ldso: /hello: Not a valid dynamic program**

Same app built with gcc works fine.
$ gcc -g -o appdir/hello hello.c

**Comment by mrragava** [comment]
ragava@dev:~/Desktop/labs/mystikos/sample-myst$ readelf -h ./appdir/hello 
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  **Type:                              EXEC (Executable file)**
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x4003e0
  Start of program headers:          64 (bytes into file)
  Start of section headers:          7016 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         9
  Size of section headers:           64 (bytes)
  Number of section headers:         35
  Section header string table index: 34


Elf file type is EXEC (Executable file)
Entry point 0x4003e0
There are 9 program headers, starting at offset 64

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  PHDR           0x0000000000000040 **0x0000000000400040** 0x0000000000400040
                 0x00000000000001f8 0x00000000000001f8  R      0x8
  INTERP         0x0000000000000238 0x0000000000400238 0x0000000000400238
                 0x000000000000001c 0x000000000000001c  R      0x1

**Comment by mrragava** [comment]
**Program header when built with gcc**

ragava@dev:~/Desktop/labs/mystikos/sample-myst$ readelf -h ./appdir/hello 
ELF Header:
  Magic:   7f 45 4c 46 02 01 01 00 00 00 00 00 00 00 00 00 
  Class:                             ELF64
  Data:                              2's complement, little endian
  Version:                           1 (current)
  OS/ABI:                            UNIX - System V
  ABI Version:                       0
  **Type:                              DYN (Shared object file)**
  Machine:                           Advanced Micro Devices X86-64
  Version:                           0x1
  Entry point address:               0x1050
  Start of program headers:          64 (bytes into file)
  Start of section headers:          16768 (bytes into file)
  Flags:                             0x0
  Size of this header:               64 (bytes)
  Size of program headers:           56 (bytes)
  Number of program headers:         11
  Size of section headers:           64 (bytes)
  Number of section headers:         34
  Section header string table index: 33

Program Headers:
  Type           Offset             VirtAddr           PhysAddr
                 FileSiz            MemSiz              Flags  Align
  **PHDR           0x0000000000000040 0x0000000000000040 0x0000000000000040**
                 0x0000000000000268 0x0000000000000268  R      0x8
  INTERP         0x00000000000002a8 0x00000000000002a8 0x00000000000002a8
                 0x000000000000001c 0x000000000000001c  R      0x1

**Comment by paulcallen** [comment]
missing clang shared libraries?
missing support in mystikos for clang shared libraries similar to problems we had with gcc shared libraries

**Comment by bodzhang** [comment]
@mrragava, Mystikos only support position independent executable. Can you try `-fPIE` on the clang command line?

**Comment by mrragava** [comment]
-pie works.
