### ISSUE TITLE
Dockerfile is out of date.

### ISSUE THREAD

**Issue by qinkunbao** [deislabs/mystikos#779]
Following the instruction from 

https://github.com/deislabs/mystikos/blob/main/docker/build-myst/README.md

I got the error information:

Collecting cryptography (from ansible==2.8.8->-r ./openenclave/scripts/ansible/requirements.txt (line 3))
  Downloading https://files.pythonhosted.org/packages/cc/98/8a258ab4787e6f835d350639792527d2eb7946ff9fc0caca9c3f4cf5dcfe/cryptography-3.4.8.tar.gz (546kB)
    Complete output from command python setup.py egg_info:

            =============================DEBUG ASSISTANCE==========================
            If you are seeing an error here please try the following to
            successfully install cryptography:

            Upgrade to the latest pip and try again. This will fix errors for most
            users. See: https://pip.pypa.io/en/stable/installing/#upgrading-pip
            =============================DEBUG ASSISTANCE==========================

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-ws9iz7uj/cryptography/setup.py", line 14, in <module>
        from setuptools_rust import RustExtension
    ModuleNotFoundError: No module named 'setuptools_rust'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-ws9iz7uj/cryptography/
The command '/bin/sh -c ./openenclave/scripts/ansible/install-ansible.sh' returned a non-zero code: 1

**Comment by vtikoo** [comment]
Thanks for reporting this. Let us know if you still see issues.
