### ISSUE TITLE
libc test failure: pthread_cancel-sem_wait

### ISSUE THREAD

**Issue by mikbras** [deislabs/mystikos#79]
This fails occasionally.

=== start test: /src/regression/pthread_cancel-sem_wait.exe
src/regression/pthread_cancel-sem_wait.c:55: seqno == 1 failed (uncontended sem_wait)
src/regression/pthread_cancel-sem_wait.c:65: seqno == 1 failed (blocking sem_wait)
Assertion failed: WEXITSTATUS(wstatus) == 0 (run.c: _run_tests: 47)
2021-02-01T21:20:33+0000.182637Z [(H)ERROR] tid(0x7f578ecf7b80) | :OE_ENCLAVE_ABORTING [/root/OpenLibOS/third_party/openenclave/openenclave/host/calls.c:_call_enclave_function_impl:56]
/root/mystikos/build/bin/myst: error: failed to enter enclave: result=OE_ENCLAVE_ABORTING
Makefile:68: recipe for target 'tests' failed
make: *** [tests] Error 1

**Comment by jxyang** [comment]
Fixed by enforcing the order between the parent and the child threads.
